/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import Database.Koneksi;
import Popup.popupdatajemaat;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import java.util.HashMap;
import java.util.Locale;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperReport;

/**
 *
 * @author oscar
 */
public class Form_PendataanJemaat extends javax.swing.JFrame {
    public String idjemaat;
private Connection conn = new Koneksi().connect();
private DefaultTableModel tabmode;
    
Object[] Baris = {"Nama Baptis", "Nama", "Tempat Lahir", "Tanggal Lahir", "Jenis Kelamin", "Status Dalam Keluarga", "Tempat Baptis", "Tanggal Baptis", "Pendidikan", "Pekerjaan", "Lingkungan",  "Alamat"};

    public Form_PendataanJemaat() {
        initComponents();
        kosong();
        aktif();
        autonumber();
        Locale locale = new Locale ("id","ID");
        Locale.setDefault(locale);
        tabmode = new DefaultTableModel(null, Baris);
    }

    protected void kosong(){
    id_jemaat.setText("");
    nma_baptis.setText("");
    nama.setText("");
    tmp_lahir.setText("");
    tgllahir.setCalendar(null);
    jk2.setText("");
    tmp_baptis.setText("");
    tglbaptis.setCalendar(null);
    pendidikan.setText("");
    pekerjaan.setText("");
    lingkungan2.setText("");
    status2.setText("");
    alamat.setText("");
    Table.removeAll();
}

    protected void aktif(){
    nma_baptis.requestFocus();
    //id_jemaat.setEnabled(false);
    Ubah.setEnabled(false); 
}
    
    protected void autonumber(){
 try{
 String sql = "SELECT ID_jemaat FROM data_jemaatgereja order by ID_jemaat asc";
 Statement stat = conn.createStatement();
 ResultSet rs=stat.executeQuery(sql);

 while(rs.next()){
 String ID_jemaat = rs.getString("ID_jemaat").substring(2);
 int nomor = Integer.parseInt(ID_jemaat) + 1;
 String nol = "";

 if (nomor<10)
 {nol = "000";}
 else if (nomor<100)
 {nol = "00";}
 else if (nomor<1000)
 {nol = "";}

 id_jemaat.setText("KK" + nol + nomor );
 }
 }
 catch (Exception e){
      JOptionPane.showMessageDialog(null,"Penomoran Salah" + e);
 }
}
    public void removeTable(){
    try{
         for(int t=tabmode.getRowCount();t>0;t--) {tabmode.removeRow(0);}    }
    catch(Exception ex){ System.out.println(ex);  } }
   
public void popupdatajemaat(){
     popupdatajemaat Pp = new popupdatajemaat();
     Pp.jemaat = this;
     Cari2.setText(idjemaat);
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        Simpan = new javax.swing.JButton();
        Ubah = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        Batal = new javax.swing.JButton();
        Kembali = new javax.swing.JButton();
        Cari2 = new javax.swing.JTextField();
        Cari = new javax.swing.JButton();
        Tambah = new javax.swing.JButton();
        jenis_kelamin = new javax.swing.JComboBox<>();
        jk2 = new javax.swing.JTextField();
        tgllahir = new com.toedter.calendar.JDateChooser();
        tmp_lahir = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        status = new javax.swing.JComboBox<>();
        status2 = new javax.swing.JTextField();
        lingkungan1 = new javax.swing.JComboBox<>();
        lingkungan2 = new javax.swing.JTextField();
        tglbaptis = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nma_baptis = new javax.swing.JTextField();
        id_jemaat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tmp_baptis = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        panelAlpha2 = new Tampilan.panelAlpha();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pendidikan = new javax.swing.JTextField();
        pekerjaan = new javax.swing.JTextField();
        pend = new javax.swing.JComboBox<>();
        Cetak = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Table.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Baptis", "Nama", "Tempat Lahir", "Tanggal Lahir", "Jenis Kelamin", "Status Dalam Keluarga", "Tempat Baptis", "Tanggal Baptis", "Pendidikan", "Pekerjaan", "Lingkungan", "Alamat"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 1200, 170));

        Simpan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/icons-save-.png"))); // NOI18N
        Simpan.setText("SIMPAN");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });
        getContentPane().add(Simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 660, -1, -1));

        Ubah.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/icons-edit.png"))); // NOI18N
        Ubah.setText("UBAH");
        Ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahActionPerformed(evt);
            }
        });
        getContentPane().add(Ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 660, -1, -1));

        Hapus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/icons-delete.png"))); // NOI18N
        Hapus.setText("HAPUS");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        getContentPane().add(Hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 660, -1, -1));

        Batal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/icons-cancel.png"))); // NOI18N
        Batal.setText("BATAL");
        getContentPane().add(Batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 660, -1, -1));

        Kembali.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/icons-back.png"))); // NOI18N
        Kembali.setText("KEMBALI");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });
        getContentPane().add(Kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 660, -1, -1));

        Cari2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Cari2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cari2ActionPerformed(evt);
            }
        });
        getContentPane().add(Cari2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 413, 240, 30));

        Cari.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/icons-hand.png"))); // NOI18N
        Cari.setText("Cari Data");
        Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariActionPerformed(evt);
            }
        });
        getContentPane().add(Cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, -1, -1));

        Tambah.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/icons-plus.png"))); // NOI18N
        Tambah.setText("TAMBAH");
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });
        getContentPane().add(Tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, 120, 40));

        jenis_kelamin.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jenis_kelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki - laki", "Perempuan" }));
        jenis_kelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenis_kelaminActionPerformed(evt);
            }
        });
        getContentPane().add(jenis_kelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 106, -1));

        jk2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(jk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 138, -1));

        tgllahir.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(tgllahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 250, -1));

        tmp_lahir.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(tmp_lahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 250, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Jenis kelamin");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tanggal Lahir ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tempat Lahir ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 20));

        alamat.setColumns(20);
        alamat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 254, -1));

        status.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ayah", "Ibu", "Anak Pertama", "Anak Kedua", "Anak Ketiga", "Anak Keempat", "Anak Kelima", "Anak keenam", "Anak Angkat", " " }));
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 104, -1));

        status2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        status2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                status2ActionPerformed(evt);
            }
        });
        getContentPane().add(status2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 140, -1));

        lingkungan1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lingkungan1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "St. Teresia", "St. Yakobus ", "St. Bernadetha", "St. Maria", "St. Lazarus", "St. Nikodemus", "St. Klara" }));
        lingkungan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lingkungan1ActionPerformed(evt);
            }
        });
        getContentPane().add(lingkungan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 230, 104, -1));

        lingkungan2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lingkungan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lingkungan2ActionPerformed(evt);
            }
        });
        getContentPane().add(lingkungan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 230, 140, -1));
        getContentPane().add(tglbaptis, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 254, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Alamat");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Status Dalam Keluarga");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Lingkungan ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tanggal Baptis");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, -1, -1));

        nma_baptis.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        nma_baptis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nma_baptisActionPerformed(evt);
            }
        });
        getContentPane().add(nma_baptis, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 250, -1));

        id_jemaat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(id_jemaat, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 250, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Baptis");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        tmp_baptis.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tmp_baptis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmp_baptisActionPerformed(evt);
            }
        });
        getContentPane().add(tmp_baptis, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 254, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tempat Baptis");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, -1));

        panelAlpha2.setBackground(new java.awt.Color(102, 255, 102));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("PENDATAAN JEMAAT GEREJA ");
        panelAlpha2.add(jLabel2);

        getContentPane().add(panelAlpha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 37));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nama ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        nama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 250, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Pendidikan");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Pekerjaan");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, -1, -1));

        pendidikan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        pendidikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pendidikanActionPerformed(evt);
            }
        });
        getContentPane().add(pendidikan, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 150, 120, -1));

        pekerjaan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(pekerjaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, 250, -1));

        pend.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        pend.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Sekolah", "TK", "SD", "SMP", "SMA/SMK", "Perguruan Tinggi" }));
        pend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pendActionPerformed(evt);
            }
        });
        getContentPane().add(pend, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 120, -1));

        Cetak.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Cetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/icons-print.png"))); // NOI18N
        Cetak.setText("CETAK");
        Cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CetakActionPerformed(evt);
            }
        });
        getContentPane().add(Cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("*Anda bisa menambahkan lebih dari satu data jemaat \n");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 410, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("sesuai jumlah anggota keluarga jemaat setelah menekan tombol tambah");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 430, 400, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/Bacground form.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        setSize(new java.awt.Dimension(1214, 738));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lingkungan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lingkungan1ActionPerformed
        // TODO add your handling code here:
        String text;
        text = (String)lingkungan1.getSelectedItem();
        lingkungan2.setText(text);
    }//GEN-LAST:event_lingkungan1ActionPerformed

    private void tmp_baptisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmp_baptisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tmp_baptisActionPerformed

    private void jenis_kelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenis_kelaminActionPerformed
        // TODO add your handling code here:
        String text;
        text = (String)jenis_kelamin.getSelectedItem();
        jk2.setText(text);
    }//GEN-LAST:event_jenis_kelaminActionPerformed

    private void lingkungan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lingkungan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lingkungan2ActionPerformed

    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String lahir = sdf.format(tgllahir.getDate());
        String baptis = sdf.format(tglbaptis.getDate());

                try{
            String namajem = nma_baptis.getText();
            String namaasl = nama.getText();
            String tmplahir = tmp_lahir.getText();
            String tgl_lahir = lahir;
            String jk = jk2.getText();
            String sta = status2.getText();
            String tmpbaptis = tmp_baptis.getText();
            String tgl_baptis = baptis;
            String pendi = pendidikan.getText();
            String kerja = pekerjaan.getText();
            String lingkungan = lingkungan2.getText();
            String ala = alamat.getText();
   
            tabmode.addRow(new Object[]{namajem, namaasl, tmplahir, tgl_lahir, jk, sta, tmpbaptis, tgl_baptis, pendi, kerja, lingkungan,  ala});
            Table.setModel(tabmode); 
            } 
            catch(Exception e) 
            { 
            System.out.println("Error : "+e); 
            }
            nma_baptis.setText("");
            nama.setText("");
            tmp_lahir.setText("");
            tgllahir.setCalendar(null);
            jk2.setText("");
            status2.setText("");
            tmp_baptis.setText("");
            tglbaptis.setCalendar(null);
            pendidikan.setText("");
            pekerjaan.setText("");
            lingkungan2.setText("");
            alamat.setText("");          
    }//GEN-LAST:event_TambahActionPerformed

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
                // TODO add your handling code here:
        //SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        //String fd = sdf.format(tanggal.getValue());
        
        String zsql = "insert into data_jemaatgereja values (?,?,?,?,?,?,?,?,?,?,?,?,?)";     
        try{
            int t = Table.getRowCount(); 
            for(int i=0; i < t ; i++) 
            {
            String Nama_jemaat = Table.getValueAt(i, 0).toString();
            String Nama = Table.getValueAt(i, 1).toString();
            String Tempat_lahir = Table.getValueAt(i, 2).toString();
            String Tanggal_lahir = Table.getValueAt(i, 3).toString();
            String Jenis_kelamin = Table.getValueAt(i, 4).toString();
            String Status = Table.getValueAt(i, 5).toString();
            String Tempat_baptis = Table.getValueAt(i, 6).toString();
            String Tanggal_baptis = Table.getValueAt(i, 7).toString();
            String Pendidikan = Table.getValueAt(i, 8).toString();
            String Pekerjaan = Table.getValueAt(i, 9).toString();
            String Lingkungan = Table.getValueAt(i, 10).toString();
            String Alamat = Table.getValueAt(i, 11).toString();
           
            PreparedStatement stat2 = conn.prepareStatement(zsql);
            //stat2.setString(1, fd);
            stat2.setString(1, id_jemaat.getText());
            stat2.setString(2, Nama_jemaat);
            stat2.setString(3, Nama);
            stat2.setString(4, Tempat_lahir);
            stat2.setString(5, Tanggal_lahir); 
            stat2.setString(6, Jenis_kelamin);
            stat2.setString(7, Status);
            stat2.setString(8, Tempat_baptis); 
            stat2.setString(9, Tanggal_baptis);
            stat2.setString(10, Pendidikan);
            stat2.setString(11, Pekerjaan);
            stat2.setString(12, Lingkungan); 
            stat2.setString(13, Alamat);
            stat2.executeUpdate(); 
            }
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");  
        }catch(Exception e) 
            { 
            System.out.println("Error : "+e);
        }
        kosong();
        autonumber();
        removeTable();
  
    }//GEN-LAST:event_SimpanActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
        int br=Table.getSelectedRow();
        String a=Table.getValueAt(br,0).toString();
        String b=Table.getValueAt(br,1).toString();
        String c=Table.getValueAt(br,2).toString();
        String d=Table.getValueAt(br,3).toString();
        String e=Table.getValueAt(br,4).toString();
        String f=Table.getValueAt(br,5).toString();
        String g=Table.getValueAt(br,6).toString();
        String h=Table.getValueAt(br,7).toString();
        String i=Table.getValueAt(br,8).toString();
        String j=Table.getValueAt(br,9).toString();
        String k=Table.getValueAt(br,10).toString();
        String l=Table.getValueAt(br,11).toString();
        

nma_baptis.setText(a);
nama.setText(b);
tmp_lahir.setText(c);
tgllahir.setDateFormatString(d);
jk2.setText(e);
status2.setText(f);
tmp_baptis.setText(g);
tglbaptis.setDateFormatString(h);
pendidikan.setText(i);
pekerjaan.setText(j);
lingkungan2.setText(k);
alamat.setText(l);
    }//GEN-LAST:event_TableMouseClicked

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
        String text;
        text = (String)status.getSelectedItem();
        status2.setText(text);
    }//GEN-LAST:event_statusActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
                int j=JOptionPane.showConfirmDialog(null,"Delete","konfirmasiDialog",JOptionPane.YES_NO_OPTION);
        if (j==0){
            String sql= "delete from data_jemaatgereja where ID_jemaat ='"+id_jemaat.getText()+"'";
            try{
                PreparedStatement stat= conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data dihapus");
                
            }
            catch(SQLException x){
                JOptionPane.showMessageDialog(null,"Data Gagagl dihapus"+x);
            }
            kosong();
            autonumber();
        }

    }//GEN-LAST:event_HapusActionPerformed

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        // TODO add your handling code here:
        Halaman_utama Pp = new Halaman_utama();
        Pp.setVisible(true);
        Pp.setResizable(false);
        dispose();
    }//GEN-LAST:event_KembaliActionPerformed

    private void status2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_status2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_status2ActionPerformed

    private void nma_baptisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nma_baptisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nma_baptisActionPerformed

    private void UbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UbahActionPerformed

    private void pendidikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pendidikanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pendidikanActionPerformed

    private void pendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pendActionPerformed
        // TODO add your handling code here:
        String text;
        text = (String)pend.getSelectedItem();
        pendidikan.setText(text);
    }//GEN-LAST:event_pendActionPerformed

    private void CetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetakActionPerformed
        // TODO add your handling code here:
       try {
            String path="C:\\Users\\oscar\\Documents\\NetBeansProjects\\Gerejaproject\\src\\Laporan\\kartukeluarga.jasper";
            HashMap parameter = new HashMap();
            parameter.put("id",Cari2.getText());
            JasperPrint print = JasperFillManager.fillReport(path,parameter,conn);
            JasperViewer.viewReport(print, false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,"Dokumen Tidak Ada "+ex);
        }

    }//GEN-LAST:event_CetakActionPerformed

    private void CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariActionPerformed
        // TODO add your handling code here:
        popupdatajemaat Pp = new popupdatajemaat();
        Pp.jemaat = this;
        Pp.setVisible(true);
        Pp.setResizable(false);
    }//GEN-LAST:event_CariActionPerformed

    private void Cari2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cari2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cari2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_PendataanJemaat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_PendataanJemaat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_PendataanJemaat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_PendataanJemaat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_PendataanJemaat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Batal;
    private javax.swing.JButton Cari;
    private javax.swing.JTextField Cari2;
    private javax.swing.JButton Cetak;
    private javax.swing.JButton Hapus;
    private javax.swing.JButton Kembali;
    private javax.swing.JButton Simpan;
    private javax.swing.JTable Table;
    private javax.swing.JButton Tambah;
    private javax.swing.JButton Ubah;
    private javax.swing.JTextArea alamat;
    private javax.swing.JTextField id_jemaat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jenis_kelamin;
    private javax.swing.JTextField jk2;
    private javax.swing.JComboBox<String> lingkungan1;
    private javax.swing.JTextField lingkungan2;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nma_baptis;
    private Tampilan.panelAlpha panelAlpha2;
    private javax.swing.JTextField pekerjaan;
    private javax.swing.JComboBox<String> pend;
    private javax.swing.JTextField pendidikan;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JTextField status2;
    private com.toedter.calendar.JDateChooser tglbaptis;
    private com.toedter.calendar.JDateChooser tgllahir;
    private javax.swing.JTextField tmp_baptis;
    private javax.swing.JTextField tmp_lahir;
    // End of variables declaration//GEN-END:variables
}
