/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Database.Koneksi;
import Popup.popupadmin;
import Popup.popuppemasukan;
import Popup.popupanggota;
import Popup.popup_lihat_pengeluaran;
/**
 *
 * @author oscar
 */
public class Form_Pengeluaran extends javax.swing.JFrame {
public String idpemasukan,nmadonatur,nmapemasukan;
    public String idadmin;
    public String idanggota, nmaanggota;
  private Connection conn = new Koneksi().connect();
private DefaultTableModel tabmode;
    
Object[] Baris ={"ID Pemasukan","Nama Pemasukan","Jenis Pemasukan","Banyak Pengeluaran","Keterangan"};

    public Form_Pengeluaran() {
        initComponents();
        kosong();
        aktif();
        autonumber();
        Locale locale = new Locale ("id","ID");
        Locale.setDefault(locale);    
        tabmode = new DefaultTableModel(null, Baris);
    }

    protected void kosong(){
id_pengeluaran.setText("");
id_admin.setText("");
id_ang.setText("");
nma_ang.setText("");
id_pemasukan.setText("");
nma_pemasukan.setText("");
jns_pemasukan.setText("");
bnyk_pengeluaran.setText("");
ket.setText("");
//Table.removeAll();
}
    
    protected void aktif(){
bnyk_pengeluaran.requestFocus();
id_pengeluaran.setEnabled(false);  
Ubah.setEnabled(false);  
}
    
    protected void autonumber(){
 try{
 String sql = "SELECT ID_pengeluaran FROM data_pengeluaran order by ID_pengeluaran asc";
 Statement stat = conn.createStatement();
 ResultSet rs=stat.executeQuery(sql);

 while(rs.next()){
 String ID_pengeluaran = rs.getString("ID_pengeluaran").substring(2);
 int nomor = Integer.parseInt(ID_pengeluaran) + 1;
 String nol = "";

 if (nomor<10)
 {nol = "000";}
 else if (nomor<100)
 {nol = "00";}
 else if (nomor<1000)
 {nol = "";}

 id_pengeluaran.setText("PG" + nol + nomor);
 }
 }
 catch (Exception e){
      JOptionPane.showMessageDialog(null,"Penomoran Salah" + e);
 }
}
    
    public void removeTable(){
    try{
         for(int t=tabmode.getRowCount();t>0;t--) {tabmode.removeRow(0);}    }
    catch(Exception ex){ System.out.println(ex);  } }

     public void popupadmin(){
     popupadmin Pp = new popupadmin();
     Pp.adm = this;
     id_admin.setText(idadmin);
     }
     public void popuppemasukan(){
     popuppemasukan Pp = new popuppemasukan();
     Pp.pem = this;
     id_pemasukan.setText(idpemasukan);
     nma_pemasukan.setText(nmadonatur);
     jns_pemasukan.setText(nmapemasukan);
 }
     public void popupanggota(){
     popupanggota Pp = new popupanggota();
     Pp.ang = this;
     id_ang.setText(idanggota);
     nma_ang.setText(nmaanggota);
     }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        Simpan = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        Ubah = new javax.swing.JButton();
        Batal = new javax.swing.JButton();
        Kembali = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        bnyk_pengeluaran = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ket = new javax.swing.JTextArea();
        Tambah = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        id_pengeluaran = new javax.swing.JTextField();
        tanggal = new javax.swing.JSpinner();
        id_admin = new javax.swing.JTextField();
        id_ang = new javax.swing.JTextField();
        nma_ang = new javax.swing.JTextField();
        id_pemasukan = new javax.swing.JTextField();
        nma_pemasukan = new javax.swing.JTextField();
        jns_pemasukan = new javax.swing.JTextField();
        Cari_admin = new javax.swing.JButton();
        Cari_anggota = new javax.swing.JButton();
        Cari_pemasukan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lihat_data = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Admin", "ID Anggota", "Nama Anggota", "ID Pemasukan", "Nama Pemasukan", "Jenis Pemasukan", "Banyak Pengeluaran", "Keterangan"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 940, 170));

        Simpan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/icons-save-.png"))); // NOI18N
        Simpan.setText("SIMPAN");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });
        getContentPane().add(Simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, -1, -1));

        Hapus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/icons-delete.png"))); // NOI18N
        Hapus.setText("HAPUS");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        getContentPane().add(Hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, -1, -1));

        Ubah.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/icons-edit.png"))); // NOI18N
        Ubah.setText("UBAH");
        Ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahActionPerformed(evt);
            }
        });
        getContentPane().add(Ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, -1, -1));

        Batal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/icons-cancel.png"))); // NOI18N
        Batal.setText("BATAL");
        Batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalActionPerformed(evt);
            }
        });
        getContentPane().add(Batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 530, -1, -1));

        Kembali.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/icons-back.png"))); // NOI18N
        Kembali.setText("KEMBALI");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });
        getContentPane().add(Kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 530, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Banyak Pengeluaran");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, -1, -1));

        bnyk_pengeluaran.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(bnyk_pengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 241, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Keterangan");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, -1, -1));

        ket.setColumns(20);
        ket.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ket.setRows(5);
        jScrollPane1.setViewportView(ket);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 241, -1));

        Tambah.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/icons-plus.png"))); // NOI18N
        Tambah.setText("TAMBAH");
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });
        getContentPane().add(Tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, 120, 30));

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("FORM PENGELUARAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, -1));

        id_pengeluaran.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(id_pengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 165, -1));

        tanggal.setModel(new javax.swing.SpinnerDateModel());
        getContentPane().add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        id_admin.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        id_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_adminActionPerformed(evt);
            }
        });
        getContentPane().add(id_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 241, -1));

        id_ang.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(id_ang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 241, -1));

        nma_ang.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        nma_ang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nma_angActionPerformed(evt);
            }
        });
        getContentPane().add(nma_ang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 241, -1));

        id_pemasukan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(id_pemasukan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 241, -1));

        nma_pemasukan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        nma_pemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nma_pemasukanActionPerformed(evt);
            }
        });
        getContentPane().add(nma_pemasukan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 241, -1));

        jns_pemasukan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jns_pemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jns_pemasukanActionPerformed(evt);
            }
        });
        getContentPane().add(jns_pemasukan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 241, -1));

        Cari_admin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Cari_admin.setText("Cari Data");
        Cari_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cari_adminActionPerformed(evt);
            }
        });
        getContentPane().add(Cari_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, -1));

        Cari_anggota.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Cari_anggota.setText("Cari Data");
        Cari_anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cari_anggotaActionPerformed(evt);
            }
        });
        getContentPane().add(Cari_anggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));

        Cari_pemasukan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Cari_pemasukan.setText("Cari Data");
        Cari_pemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cari_pemasukanActionPerformed(evt);
            }
        });
        getContentPane().add(Cari_pemasukan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Admin");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 150, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ID Anggota");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 150, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nama Anggota");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 150, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID Pemasukan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 150, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nama Pemasukan");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 150, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jenis Pemasukan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 150, -1));

        lihat_data.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lihat_data.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/icons-eye.png"))); // NOI18N
        lihat_data.setText("Lihat Data");
        lihat_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihat_dataActionPerformed(evt);
            }
        });
        getContentPane().add(lihat_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, 160, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("*Anda bisa menambahkan lebih dari satu pengeluaran ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 290, 310, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("setelah menekan tombol tambah");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 190, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/Background Form kecil.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(969, 612));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jns_pemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jns_pemasukanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jns_pemasukanActionPerformed

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        // TODO add your handling code here:
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd (HH:mm:ss)");
        String fd = sdf.format(tanggal.getValue());

        String zsql = "insert into data_pengeluaran values (?,?,?,?,?,?,?,?,?,?)";
        try{
            int t = Table.getRowCount();
            for(int i=0; i < t ; i++)
            {
                String ID_pemasukan = Table.getValueAt(i, 0).toString();
                String Nama_Pemasukan = Table.getValueAt(i, 1).toString();
                String Jenis_Pemasukan = Table.getValueAt(i, 2).toString();
                String Banyak_Pengeluaran = Table.getValueAt(i, 3).toString();
                String Keterangan = Table.getValueAt(i, 4).toString();

                PreparedStatement stat2 = conn.prepareStatement(zsql);
                stat2.setString(1, id_pengeluaran.getText());
                stat2.setString(2, fd);
                stat2.setString(3, id_admin.getText());
                stat2.setString(4, id_ang.getText());
                stat2.setString(5, nma_ang.getText());
                stat2.setString(6, ID_pemasukan);
                stat2.setString(7, Nama_Pemasukan);
                stat2.setString(8, Jenis_Pemasukan);
                stat2.setString(9, Banyak_Pengeluaran);
                stat2.setString(10, Keterangan);
                stat2.executeUpdate();
            }
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
        }catch(Exception e)
        {
            System.out.println("Error : "+e);
        }
        kosong();
        autonumber();
        removeTable();

    }//GEN-LAST:event_SimpanActionPerformed

    private void UbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UbahActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        int index = Table.getSelectedRow();
        tabmode.removeRow(index);
        Table.setModel(tabmode);

        id_pemasukan.setText("");
        nma_pemasukan.setText("");
        jns_pemasukan.setText("");
        bnyk_pengeluaran.setText("");
        ket.setText("");

    }//GEN-LAST:event_HapusActionPerformed

    private void BatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalActionPerformed
        // TODO add your handling code here:
        kosong();
        autonumber();
    }//GEN-LAST:event_BatalActionPerformed

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        // TODO add your handling code here:
        Halaman_utama Pp = new Halaman_utama();
        Pp.setVisible(true);
        Pp.setResizable(false);
        dispose();
    }//GEN-LAST:event_KembaliActionPerformed

    private void Cari_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cari_adminActionPerformed
        // TODO add your handling code here:
        popupadmin Pp = new popupadmin();
        Pp.adm = this;
        Pp.setVisible(true);
        Pp.setResizable(false);
    }//GEN-LAST:event_Cari_adminActionPerformed

    private void Cari_pemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cari_pemasukanActionPerformed
        // TODO add your handling code here:
        popuppemasukan Pp = new popuppemasukan();
        Pp.pem = this;
        Pp.setVisible(true);
        Pp.setResizable(false);
    }//GEN-LAST:event_Cari_pemasukanActionPerformed

    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
        // TODO add your handling code here:
               try{
            
            String id = id_pemasukan.getText();
            String nma_do = nma_pemasukan.getText();
            String nma_msuk = jns_pemasukan.getText();
            String bnyk = bnyk_pengeluaran.getText();
            String ke = ket.getText();

            tabmode.addRow(new Object[]{id,nma_do,nma_msuk,bnyk,ke});
            Table.setModel(tabmode);
        }
        catch(Exception e)
        {
            System.out.println("Error : "+e);
        }
        id_pemasukan.setText("");
        nma_pemasukan.setText("");
        jns_pemasukan.setText("");
        bnyk_pengeluaran.setText("");
        ket.setText("");
    }//GEN-LAST:event_TambahActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
               int br=Table.getSelectedRow();
        String a=Table.getValueAt(br,0).toString();
        String b=Table.getValueAt(br,1).toString();
        String c=Table.getValueAt(br,2).toString();
        String d=Table.getValueAt(br,3).toString();
        String e=Table.getValueAt(br,4).toString();
   
        
        id_pemasukan.setText(a);
        nma_pemasukan.setText(b);
        jns_pemasukan.setText(c);
        bnyk_pengeluaran.setText(d);
        ket.setText(e);
    }//GEN-LAST:event_TableMouseClicked

    private void Cari_anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cari_anggotaActionPerformed
        // TODO add your handling code here:
        popupanggota Pp = new popupanggota();
        Pp.ang = this;
        Pp.setVisible(true);
        Pp.setResizable(false);
    }//GEN-LAST:event_Cari_anggotaActionPerformed

    private void nma_angActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nma_angActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nma_angActionPerformed

    private void nma_pemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nma_pemasukanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nma_pemasukanActionPerformed

    private void id_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_adminActionPerformed

    private void lihat_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihat_dataActionPerformed
        // TODO add your handling code here:
        popup_lihat_pengeluaran Pp = new popup_lihat_pengeluaran();
        Pp.keluar = this;
        Pp.setVisible(true);
        Pp.setResizable(false);
    }//GEN-LAST:event_lihat_dataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Pengeluaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Batal;
    private javax.swing.JButton Cari_admin;
    private javax.swing.JButton Cari_anggota;
    private javax.swing.JButton Cari_pemasukan;
    private javax.swing.JButton Hapus;
    private javax.swing.JButton Kembali;
    private javax.swing.JButton Simpan;
    private javax.swing.JTable Table;
    private javax.swing.JButton Tambah;
    private javax.swing.JButton Ubah;
    private javax.swing.JTextField bnyk_pengeluaran;
    private javax.swing.JTextField id_admin;
    private javax.swing.JTextField id_ang;
    private javax.swing.JTextField id_pemasukan;
    private javax.swing.JTextField id_pengeluaran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jns_pemasukan;
    private javax.swing.JTextArea ket;
    private javax.swing.JButton lihat_data;
    private javax.swing.JTextField nma_ang;
    private javax.swing.JTextField nma_pemasukan;
    private javax.swing.JSpinner tanggal;
    // End of variables declaration//GEN-END:variables
}
