/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan;
import java.sql.Connection;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Locale;
import static java.util.Objects.hash;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Database.Koneksi;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.JRException;

public class Laporan extends javax.swing.JFrame {
private Connection conn = new Koneksi().connect();
private DefaultTableModel tabmode;

    public Laporan() {
        initComponents();
        Locale locale = new Locale ("id","ID");
        Locale.setDefault(locale);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAlpha8 = new Tampilan.panelAlpha();
        Form_kolekte = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        kolekte1 = new javax.swing.JComboBox<>();
        kolekte2 = new javax.swing.JTextField();
        KEMBALI = new javax.swing.JButton();
        panelAlpha3 = new Tampilan.panelAlpha();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        panelAlpha10 = new Tampilan.panelAlpha();
        Form_Anggota = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelAlpha4 = new Tampilan.panelAlpha();
        Form_jadwal = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        panelAlpha9 = new Tampilan.panelAlpha();
        jLabel26 = new javax.swing.JLabel();
        tanggal = new javax.swing.JSpinner();
        panelAlpha2 = new Tampilan.panelAlpha();
        tanggal3 = new com.toedter.calendar.JDateChooser();
        tanggal4 = new com.toedter.calendar.JDateChooser();
        jButton7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAlpha8.setBackground(new java.awt.Color(0, 0, 0));
        panelAlpha8.setOpaque(false);

        Form_kolekte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/icon data kolekte.png"))); // NOI18N
        Form_kolekte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Form_kolekteActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("LAPORAN KOLEKTE HARI MINGGU");

        kolekte1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        kolekte1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kolekte 1", "Kolekte 2" }));
        kolekte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolekte1ActionPerformed(evt);
            }
        });

        kolekte2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelAlpha8Layout = new javax.swing.GroupLayout(panelAlpha8);
        panelAlpha8.setLayout(panelAlpha8Layout);
        panelAlpha8Layout.setHorizontalGroup(
            panelAlpha8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha8Layout.createSequentialGroup()
                .addGroup(panelAlpha8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAlpha8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(kolekte1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kolekte2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAlpha8Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(panelAlpha8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(panelAlpha8Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(Form_kolekte, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelAlpha8Layout.setVerticalGroup(
            panelAlpha8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Form_kolekte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAlpha8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kolekte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kolekte2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(panelAlpha8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 260, 190));

        KEMBALI.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        KEMBALI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/icons-back.png"))); // NOI18N
        KEMBALI.setText("KEMBALI");
        KEMBALI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KEMBALIActionPerformed(evt);
            }
        });
        getContentPane().add(KEMBALI, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 135, 44));

        panelAlpha3.setBackground(new java.awt.Color(0, 0, 0));
        panelAlpha3.setOpaque(false);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/icon pemasukan.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LAPORAN PEMASUKAN");

        javax.swing.GroupLayout panelAlpha3Layout = new javax.swing.GroupLayout(panelAlpha3);
        panelAlpha3.setLayout(panelAlpha3Layout);
        panelAlpha3Layout.setHorizontalGroup(
            panelAlpha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha3Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(panelAlpha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlpha3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlpha3Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        panelAlpha3Layout.setVerticalGroup(
            panelAlpha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(panelAlpha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 370, 190, 180));

        panelAlpha10.setBackground(new java.awt.Color(0, 0, 0));
        panelAlpha10.setOpaque(false);

        Form_Anggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/Anggota.png"))); // NOI18N
        Form_Anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Form_AnggotaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LAPORAN ANGGOTA DPP");

        javax.swing.GroupLayout panelAlpha10Layout = new javax.swing.GroupLayout(panelAlpha10);
        panelAlpha10.setLayout(panelAlpha10Layout);
        panelAlpha10Layout.setHorizontalGroup(
            panelAlpha10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(30, 30, 30))
            .addGroup(panelAlpha10Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Form_Anggota, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAlpha10Layout.setVerticalGroup(
            panelAlpha10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Form_Anggota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        getContentPane().add(panelAlpha10, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 190, 190));

        panelAlpha4.setBackground(new java.awt.Color(0, 0, 0));
        panelAlpha4.setOpaque(false);

        Form_jadwal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/icon jadwal.png"))); // NOI18N
        Form_jadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Form_jadwalActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cetak");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Jadwal Pelayanan Gereja");

        javax.swing.GroupLayout panelAlpha4Layout = new javax.swing.GroupLayout(panelAlpha4);
        panelAlpha4.setLayout(panelAlpha4Layout);
        panelAlpha4Layout.setHorizontalGroup(
            panelAlpha4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha4Layout.createSequentialGroup()
                .addGroup(panelAlpha4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAlpha4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Form_jadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAlpha4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19))
                    .addGroup(panelAlpha4Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAlpha4Layout.setVerticalGroup(
            panelAlpha4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Form_jadwal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelAlpha4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 170, 190));

        panelAlpha9.setBackground(new java.awt.Color(153, 255, 153));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel26.setText("LAPORAN");

        javax.swing.GroupLayout panelAlpha9Layout = new javax.swing.GroupLayout(panelAlpha9);
        panelAlpha9.setLayout(panelAlpha9Layout);
        panelAlpha9Layout.setHorizontalGroup(
            panelAlpha9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha9Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel26)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        panelAlpha9Layout.setVerticalGroup(
            panelAlpha9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelAlpha9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        tanggal.setModel(new javax.swing.SpinnerDateModel());
        getContentPane().add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        panelAlpha2.setBackground(new java.awt.Color(0, 0, 0));
        panelAlpha2.setOpaque(false);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("CETAK");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LAPORAN PENGELUARAN");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("AWAL");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("AKHIR");

        javax.swing.GroupLayout panelAlpha2Layout = new javax.swing.GroupLayout(panelAlpha2);
        panelAlpha2.setLayout(panelAlpha2Layout);
        panelAlpha2Layout.setHorizontalGroup(
            panelAlpha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha2Layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(115, 115, 115))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlpha2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(tanggal3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tanggal4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(panelAlpha2Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelAlpha2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(82, 82, 82))
        );
        panelAlpha2Layout.setVerticalGroup(
            panelAlpha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelAlpha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanggal4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tanggal3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAlpha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        getContentPane().add(panelAlpha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 390, 180));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/Background laporan.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(977, 612));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Form_kolekteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Form_kolekteActionPerformed
        // TODO add your handling code here:
        try {
            String path="C:\\Users\\oscar\\Documents\\NetBeansProjects\\Gerejaproject\\src\\Laporan\\datakolekte.jasper";
            HashMap parameter = new HashMap();
            parameter.put("kolekteke",kolekte2.getText());
            JasperPrint print = JasperFillManager.fillReport(path,parameter,conn);
            JasperViewer.viewReport(print, false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,"Dokumen Tidak Ada "+ex);
        }
    }//GEN-LAST:event_Form_kolekteActionPerformed

    private void Form_jadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Form_jadwalActionPerformed
        // TODO add your handling code here:
        try {
            String path="C:\\Users\\oscar\\Documents\\NetBeansProjects\\Gerejaproject\\src\\Laporan\\jadwalpastoran.jasper";
            HashMap parameter = new HashMap();
            //parameter.put("no",txtno.getText());
            JasperPrint print = JasperFillManager.fillReport(path,parameter,conn);
            JasperViewer.viewReport(print, false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,"Dokumen Tidak Ada "+ex);
        }
    }//GEN-LAST:event_Form_jadwalActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            String path="C:\\Users\\oscar\\Documents\\NetBeansProjects\\Gerejaproject\\src\\Laporan\\pemasukan.jasper";
            HashMap parameter = new HashMap();
            //parameter.put("no",txtno.getText());
            JasperPrint print = JasperFillManager.fillReport(path,parameter,conn);
            JasperViewer.viewReport(print, false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,"Dokumen Tidak Ada "+ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            String dr = sdf.format(tanggal3.getDate());
            String sp = sdf.format(tanggal4.getDate());
            Timestamp rd = Timestamp.valueOf(dr);
            Timestamp ps = Timestamp.valueOf(sp);
            String path="C:\\Users\\oscar\\Documents\\NetBeansProjects\\Gerejaproject\\src\\Laporan\\pengeluaran.jasper";
            HashMap parameter = new HashMap();
            parameter.put("awalan",rd);
            parameter.put("akhiran",ps);
            JasperPrint print = JasperFillManager.fillReport(path,parameter,conn);
            JasperViewer.viewReport(print, false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,"Dokumen Tidak Ada "+ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void Form_AnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Form_AnggotaActionPerformed
        // TODO add your handling code here:
    try {
            String path="C:\\Users\\oscar\\Documents\\NetBeansProjects\\Gerejaproject\\src\\Laporan\\anggotaDPP.jasper";
            HashMap parameter = new HashMap();
            //parameter.put("no",txtno.getText());
            JasperPrint print = JasperFillManager.fillReport(path,parameter,conn);
            JasperViewer.viewReport(print, false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,"Dokumen Tidak Ada "+ex);
        }    
    }//GEN-LAST:event_Form_AnggotaActionPerformed

    private void KEMBALIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KEMBALIActionPerformed
        // TODO add your handling code here:
        new Halaman_utama().setVisible(true);
        dispose();
    }//GEN-LAST:event_KEMBALIActionPerformed

    private void kolekte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolekte1ActionPerformed
        // TODO add your handling code here:
        String text;
        text = (String)kolekte1.getSelectedItem();
        kolekte2.setText(text);
    }//GEN-LAST:event_kolekte1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Form_Anggota;
    private javax.swing.JButton Form_jadwal;
    private javax.swing.JButton Form_kolekte;
    private javax.swing.JButton KEMBALI;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> kolekte1;
    private javax.swing.JTextField kolekte2;
    private Tampilan.panelAlpha panelAlpha10;
    private Tampilan.panelAlpha panelAlpha2;
    private Tampilan.panelAlpha panelAlpha3;
    private Tampilan.panelAlpha panelAlpha4;
    private Tampilan.panelAlpha panelAlpha8;
    private Tampilan.panelAlpha panelAlpha9;
    private javax.swing.JSpinner tanggal;
    private com.toedter.calendar.JDateChooser tanggal3;
    private com.toedter.calendar.JDateChooser tanggal4;
    // End of variables declaration//GEN-END:variables
}
